# Generated by Django 4.2.4 on 2023-09-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_create_todo_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
        migrations.AddField(
            model_name="todo",
            name="state",
            field=models.CharField(
                choices=[
                    ("D", "Done"),
                    ("F", "Finished"),
                    ("I", "In Progress"),
                    ("P", "Pending"),
                    ("O", "Overdue"),
                ],
                default="P",
                max_length=2,
                verbose_name="State",
            ),
        ),
    ]
