# Generated by Django 4.2.4 on 2023-09-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_change_due_to_date_in_todo_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="state",
        ),
        migrations.AddField(
            model_name="todo",
            name="is_done",
            field=models.BooleanField(default=False, verbose_name="Is Done"),
        ),
    ]
